### ISSUE TITLE
Update Shuttle versions

### ISSUE THREAD

**Issue by joshua-mo-143** [fatfingers23/trackscape-discord-bot#41]
We should update the Shuttle versions of the API and Bot as well as removing dependencies on `shuttle-persist` (it's outdated, although Shuttle is currently looking into alternatives). The reason behind this is so that should users want to *not* deploy on Shuttle for any reason, we can easily facilitate this (by creating a separate standalone binary as part of a different issue/PR) because we'll have a much more accurate picture of what it would take to *actually* migrate off of Shuttle. Also, as much as I am working for Shuttle professionally, unnecessary vendor lock-in is absolutely something that should be avoided.

Regarding Shuttle Persist - the bot and API don't seem to be using it that heavily. Maybe if we grab the keys we need straight from env then use maybe `secrecy` or something, we can protect it better that way? `bincode` (which `shuttle-persist` relies on) is not particularly secure in any manner.

## To-do:
- [x] Find a suitable replacement for the persist instance and implement it (since we're just saving and loading an API key, maybe we can store this in mongo? Or we can just grab it from env since there is no meaningful reason for having it in persist besides maybe not needing to provide it the next deployment)
- [x] Implement the replacement
- [x] Upgrade Shuttle versions
- [x] Update the docs/README

**Comment by fatfingers23** [comment]
This sounds great and would be a great addition to the project! 

The migration away from Shuttle Persist would be a path a bit like this;
1. The management key found in [trackscape-discord-api/main.rs](https://github.com/fatfingers23/trackscape-discord-bot/blob/48e1e4773d5ec53c6fb941c6572244c9c730a9e4/trackscape-discord-api/src/main.rs#L64) can just be loaded from the env. It is used for some communications between the API and Discord bot, each with access to the same `.env`.
2.  For [line73ish](https://github.com/fatfingers23/trackscape-discord-bot/blob/48e1e4773d5ec53c6fb941c6572244c9c730a9e4/trackscape-discord-api/src/main.rs#L75) it is getting a mapping of item names to GE item id so it has a mapping for those when looking up GE prices since it is done by ID and not item name. It's calling this URL `https://prices.runescape.wiki/api/v1/osrs/mapping`. We want it to happen on API start so that when new items are added, we can just reboot the API and get the updated items and IDs. I think this would be fine to have in the Redis cache, and I can also set a week expiration since updates are usually weekly and be a little overlap on this. So it would be a GetOrSet. If the key is not set(expired), it calls the API and re-caches it.
3. [line 86ish](https://github.com/fatfingers23/trackscape-discord-bot/blob/48e1e4773d5ec53c6fb941c6572244c9c730a9e4/trackscape-discord-api/src/main.rs#L86) is the same story. Each OSRS quest has a difficulty. This allows each discord to cut down on this message type. So easy quests happen a lot more often and send many messages, whereas higher levels ones happen less, but should be celebrated more. It can be cached in Redis with a week expiration as well. 

I think thats about it for shuttle persist!

For updating Shuttle versions I also agree it is something we should do. I had some concerns about serenity because of an API change they had going to version 12. But looks like we are at 12.0 already so should not be that bad of an upgrade! 

Thanks you for the great issue! After reviewing where we are using shuttle-persist I think we can provide a better product with putting that data in Redis since it will expire instead of depending on container restarts. Any other questions feel free to let me know!
